### PR TITLE
 share() method has depreciated in Laravel 5.4 

### PR DESCRIPTION
**Pull request by ebisbe**

### CODE REVIEW

**Comment by ebisbe** [comment]
Error on: 

Caused by

GuzzleHttp\Exception\ConnectException: cURL error 35: gnutls_handshake() failed: A TLS fatal alert has been received. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by pulkitjalan** [comment]
Thanks @ebisbe, please can you undo/fix the changes to the `.gitignore` file and i'll merge in the PR.

**Comment by ebisbe** [comment]
@pulkitjalan Sorry just wanted to add .idea. This is fine?

**Comment by pulkitjalan** [comment]
yea sure `.idea` is fine to add

**Comment by pulkitjalan** [comment]
Thanks

**Comment by ebisbe** [comment]
Will you make a new release?

**Comment by pulkitjalan** [comment]
done

**Pull request merged**
