### PR TITLE
Support for Laravel 9

### LINKED ISSUE #49: Laravel 9 Support
Can this be updated to allow Laravel 9 support? Currently getting this when tried to install:

```
Problem 1
    - Root composer.json requires pulkitjalan/geoip ^5.1 -> satisfiable by pulkitjalan/geoip[5.1.0].
    - pulkitjalan/geoip 5.1.0 requires illuminate/support ^5.8|^6|^7|^8 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

### PR DESCRIPTION
**Pull request by darthsoup**
add support for laravel 9
fixes #49

### CODE REVIEW

**Review by pulkitjalan — APPROVED** [review]

**Comment by ajsheldon93** [comment]
Can this be tagged for release? Thanks!

**Comment by nikoumhook** [comment]
how can i do the release ?

**Comment by darthsoup** [comment]
ping @pulkitjalan

**Comment by Abhi0725** [comment]
@pulkitjalan can you please do the release for this merge?

**Pull request merged**
